### ISSUE TITLE
Add check for correct units in NXdisk_chopper

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/chexus#3]
I have seen some files with missing frequency units (or units '' instead of 'Hz').

**Comment by jokasimr** [comment]
What should happen if the unit is not 'Hz' do we raise or warn or replace it silently?

**Comment by jl-wynen** [comment]
Chexus can't replace the unit, only warn about it. Also, it just needs to a frequency, doesn't matter which one.

The loader in scippneutron used to assign Hz if there is no unit. But I just removed that.

**Comment by jokasimr** [comment]
I have a PR for this, but I don't have permission to update the issue `assignees` field or push to the repo.
