### ISSUE TITLE
`v24.6.0` PyPI release lacks `--root-path` command line flag

### ISSUE THREAD

**Issue by g5t** [scipp/chexus#31]
It appears that the most-recent release was made the day before the `-r`/`--root-path` flag was added into `main`

https://github.com/scipp/chexus/blob/db3be5bed92d6d627a5311e8fa672bf5aa75860d/src/chexus/__main__.py#L35-L41

**Comment by nvaytet** [comment]
I started a new release build. Hopefully it completes :crossed_fingers:

**Comment by nvaytet** [comment]
Should be released now.

**Comment by g5t** [comment]
:tada: It's available with `-r` on PyPI, thanks!
