### ISSUE TITLE
Check `event_id` is a subset of `detector_number`

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/chexus#34]
Given an NXdetector, it should have a `detector_number`. If it contains an NXevent_data, the values of its `event_id` dataset should be contained in the set of detector numbers.

Add a new check for this.

**Comment by jokasimr** [comment]
There's very little information in https://manual.nexusformat.org/classes/base_classes/NXdetector.html about what `detector_number` actually is and how they are related to `event_id` in https://manual.nexusformat.org/classes/base_classes/NXevent_data.html.

In `NXevent_data` it just says "There will be extra information in the NXdetector to convert event_id to detector_number."
Where does it say that `event_id` corresponds to values in `detector_number`? Or is that an ESS convention?

**Comment by SimonHeybrock** [comment]
It is not an ESS convention as far as I am aware. I have never seen any "extra information" in an NXdetector that would allow for a different conversion.

**Comment by SimonHeybrock** [comment]
Not sure where the problem is. Is the description unclear?

**Comment by jokasimr** [comment]
The description is clear. Just saying, right now chexus doesn't load datasets: https://github.com/scipp/chexus/blob/8ee7988a246c950c112225e550ba818f4025f4a6/src/chexus/hdf5.py#L52
