### ISSUE TITLE
Base class `depends_on` children missing target

### ISSUE THREAD

**Issue by g5t** [scipp/chexus#7]
All of the NeXus base class 'beamline objects' have an optional `depends_on` child (c.f., [NXaperture](https://manual.nexusformat.org/classes/base_classes/NXaperture.html#nxaperture) which lists it as the first non-attribute in its structure)

These are represented in the JSON NeXus structure as `dataset` `module` entries as children under the object (e.g., search for `depends_on` in [a kafka-to-nexus test JSON NeXus structure file](https://gitlab.esss.lu.se/ecdc/ess-dmsc/kafka-to-nexus/-/blob/main/integration-tests/commands/nexus_structure.json?ref_type=heads)) which look something like
`{"module": "dataset", "config": {"name": "depends_on", "type": "string", "values": "/reference/path"}}`

Any `module` of type `dataset` with string-valued `values` in its `config` field is _always_ written as an array of strings by `kafka-to-nexus` (ultimately by [`writeStringDataset`](https://gitlab.esss.lu.se/ecdc/ess-dmsc/kafka-to-nexus/-/blob/main/src/HDFOperations.cpp?ref_type=heads#L243-263))

Therefore, the `depends_on` target written to a NeXus HDF5 file from the specification above would be read as a numpy array with representation `['/reference/path']`; which fails the `chexus` target check since it is not a string.

Either the file writer needs to be modified to produce scalar string values in this (and other?) case, or `chexus` should allow for single-valued arrays where scalars are expected.

**Comment by SimonHeybrock** [comment]
From my point of view this is not valid NeXus, therefore we do not allow it. If you have explicit information that says it is valid NeXus we can change it.

**Comment by g5t** [comment]
The `NXaperture` specification says `depends_on` should be an [`NX_CHAR`](https://manual.nexusformat.org/nxdl-types.html#nx-char) which says
> String arrays cannot be used where only a string is expected (title, start_time, end_time, NX_class attribute,…). 

If you're willing to claim that one should expect only a string for `depends_on` (or that it is an NX_class attribute) then your interpretation is correct.
